{
 "title": "LeakSignal Metrics",
 "description": "LeakSignal Sensitive Data Monitoring and Performance",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_time_bucket,service)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "WASM Active V8",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_wasm_envoy_wasm_runtime_v8_active{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{service=~\"$service\",envoy_cluster_name=~\"$cluster\"})  - sum(envoy_cluster_membership_total{service=~\"$service\",envoy_cluster_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{service=~\"$service\",envoy_cluster_name=~\"$cluster\"})-sum(envoy_cluster_membership_healthy{service=~\"$service\",envoy_cluster_name=~\"$cluster\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Sensitive Data per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(rate(ls____ssn_count{}[1m]), 0.0)",
     "legendFormat": "SSN"
    },
    {
     "expr": "clamp_min(rate(ls____phone_number_count{}[1m]), 0.0)",
     "legendFormat": "Phone Number"
    }
   ]
  },
  {
   "title": "Upstream Request Time (buckets)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$service\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Downstream Request Time (buckets)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_bucket{service=~\"$service\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upstream Total time for request/response (99th %ile) envoy_cluster_upstream_rq_time_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$service\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Downstream Total time for request/response (99th %ile) envoy_http_downstream_rq_time_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_http_downstream_rq_time_bucket{service=~\"$service\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upstream QPS (by cluster) envoy_cluster_upstream_rq_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_total{}[60s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream QPS envoy_cluster_upstream_rq_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Total Requests (combined async-client and ingress-http) envoy_http_rq_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_rq_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Responses downstream_rq_completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_completed{}[1m])) ",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",service=~\"$service\"}[1m])) by (service,envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}}) - in"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - in"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - out"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{service=~\"$service\",envoy_cluster_name=~\"$cluster\"}) by (service,envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Downstream Total Requests envoy_http_downstream_rq_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\",service=~\"$service\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\",service=~\"$service\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{service=~\"$service\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Requests envoy_cluster_external_upstream_rq",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq{envoy_response_code=\"200\"})"
    }
   ]
  }
 ]
}