static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8081
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/test"
                route:
                  cluster: python_service
              - match:
                  prefix: "/node"
                route:
                  cluster: node_test_service
              - match:
                  prefix: "/"
                route:
                  cluster: web_service

          http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "leaksignal"
                root_id: "leaksignal"
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  vm_id: "leaksignal_proxy"
                  code:
                    remote:
                      http_uri:
                        uri: https://ingestion.app.leaksignal.com/s3/leakproxy/2022_10_16_16_18_40_fda6eb2/leakproxy.wasm
                        timeout:
                          seconds: 10
                        cluster: leaksignal_infra
                      sha256: 209dc506b952de611e22c9756678aa773492aa0b59a9dc4df197b8cc206fdeed
                      retry_policy:
                        num_retries: 10
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: web_service
    type: strict_dns
    lb_policy: round_robin
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
      - priority: HIGH
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
    load_assignment:
      cluster_name: webgoat
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: webgoat-service
                port_value: 8080
  - name: python_service
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: python
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: python-service
                port_value: 8087
  - name: echo_service
    type: strict_dns
    lb_policy: round_robin
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
      - priority: HIGH
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
    load_assignment:
      cluster_name: echo
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: echo-service
                port_value: 8082
  - name: node_test_service
    type: strict_dns
    lb_policy: round_robin
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
      - priority: HIGH
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000
    load_assignment:
      cluster_name: node-test
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: node-test-service
                port_value: 8088
  - name: leaksignal_infra
    type: strict_dns
    http2_protocol_options: {}
    dns_lookup_family: V4_PREFERRED
    lb_policy: round_robin
    load_assignment:
      cluster_name: leaksignal_infra0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ingestion.app.leaksignal.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: ingestion.app.leaksignal.com
        common_tls_context:
          validation_context:
            match_typed_subject_alt_names:
            - san_type: DNS
              matcher:
                exact: ingestion.app.leaksignal.com
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
bootstrap_extensions:
  - name: envoy.bootstrap.wasm
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
      singleton: true
      config:
        name: "leaksignal_service"
        configuration:
          "@type": type.googleapis.com/google.protobuf.StringValue
          value: |
            local_policy:
              categories:
                ssn:
                  Matchers:
                    regexes:
                      - "(?!(\\d){3}(-| |)\\1{2}\\2\\1{4})(?!666|000|9\\d{2})(\\b\\d{3}(-| |)(?!00)\\d{2}\\4(?!0{4})\\d{4}\\b)"
                credit_card:
                  Matchers:
                    regexes:
                      - "[^0-9](?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})[^0-9]"
                    regex_strip: 1
                email:
                  Matchers:
                    regexes:
                      - "[a-zA-Z0-9_.+-]{2,}@[a-zA-Z0-9-]{3,}\\.[a-zA-Z0-9-.]{2,}"
                    ignore:
                      - example@example.com
                phone_number:
                  Matchers:
                    regexes:
                      - "[^0-9](?:\\+1[\\s.-])?(?:\\d{3}|\\(\\d{3}\\))[\\s.-]\\d{3}[\\s.-]\\d{4}[^0-9]"
                    regex_strip: 1
                address:
                  Matchers:
                    regexes:
                      - "(?i)[0-9]{2,6}\\s+([a-zà-ú]+\\s+){1,2}(highway|autoroute|north|nord|south|sud|east|est|west|ouest|avenue|lane|voie|ruelle|road|rue|route|drive|boulevard|circle|cercle|street|cer\\.?|cir\\.?|blvd\\.?|hway\\.?|st\\.?|aut\\.?|ave\\.?|ln\\.?|rd\\.?|hw\\.?|dr\\.?)"
                rce_root:
                  Matchers:
                    regexes:
                      - "\\broot\\b"
                rce_ls:
                  Matchers:
                    regexes:
                      - "\\bdrwx"
                rce_privatekey:
                  Matchers:
                    regexes:
                      - "\\bPRIVATE KEY\\b"
                rce_ifconfig:
                  Matchers:
                    regexes:
                      - "\\bether\\b"        
                
              endpoints:
                - matches: "**"
                  token_extractor:
                    location: request_cookie
                    header: _auth_example
                    regex: .*
                  config:
                    credit_card: {}
                    ssn: {}
                    email: {}
                      # report_style: partial_sha256
                      # report_bits: 24
                    phone_number: {}
                    rce_root: {}
                    rce_ls: {}
                    rce_privatekey: {}
                    rce_ifconfig: {}
              collect_matched_values: true
        vm_config:
          runtime: "envoy.wasm.runtime.v8"
          vm_id: "leaksignal_service"
          code:
            remote:
              http_uri:
                uri: https://ingestion.app.leaksignal.com/s3/leakproxy/2022_10_16_16_18_40_fda6eb2/leakproxy.wasm
                timeout:
                  seconds: 10
                cluster: leaksignal_infra
              sha256: 209dc506b952de611e22c9756678aa773492aa0b59a9dc4df197b8cc206fdeed
              retry_policy:
                num_retries: 10

admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901