apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - image: example/pythonserver
        name: python-v1
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
         - containerPort: 3001
           hostPort: 3001
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: python-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: ClusterIP

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'python-hostname'"
  # and forward the request to one of them
  selector:
    app: python

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - name: http
      protocol: TCP
      port: 8087
      targetPort: 3001
